FROM ubuntu

COPY server /usr/tic/server
COPY lib /usr/tic/lib

RUN apt-get update \
	&& apt-get install -y --no-install-recommends \
		gcc-5 \
		build-essential \
	&& rm -rf /var/lib/apt/lists/*

WORKDIR /usr/tic/
RUN tr -d '\r'

WORKDIR /usr/tic/lib/lib_src
RUN make re

RUN cp /usr/tic/lib/lib_src/libmy.a /usr/tic/server/libmy.a

WORKDIR /usr/tic/server
RUN make re
RUN chmod 777 /usr/tic/server/server

RUN ls -R /usr/tic/server/

CMD ["/usr/tic/server/server", "--port", "980", "-v"]
